apiVersion: v1
kind: Pod

metadata:
  name: hello

spec:
  containers:
    - name: nginx-container
      image: nginx
      command: ["sh", "-c", "echo Hello; sleep 5"]
      ports:
        - containerPort: 8081

  restartPolicy: Never
