apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DB_USER: "admin"
  DB_PASS: "supersecretpassword"
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
spec:
  containers:
    - name: app-container
      image: nginx:alpine
      envFrom:
        - secretRef:
            name: app-secret
